// Generated by scripts/vendor-web-assets.py -- do not edit by hand.
// Regenerate with: scripts/vendor-web-assets.py --sync
package com.garfiec.librechat.feature.chat.components.web

/**
 * Every vendored web asset, as a path under `files/web/` in compose resources.
 *
 * iOS copies these out of the framework bundle on first use: WKWebView refuses to
 * load local subresources for a page handed to `loadHTMLString`, so the HTML and the
 * scripts it references must sit together in one directory it has read access to.
 * Android serves them straight from `file:///android_asset/` and never reads this.
 */
internal object VendoredWebAssets {
    const val ROOT: String = "files/web"

    /**
     * One real file, used to locate the directory the others sit in. Compose
     * Resources can resolve a URI for a file but not for a directory, so the base
     * URL is derived by resolving this and trimming the tail back off.
     */
    const val ANCHOR: String = "katex/LICENSE"

    /**
     * Digest of every vendored file's content hash.
     *
     * iOS decides whether its copy is current by comparing a stored manifest against
     * this one. The file list alone cannot answer that: the pinned filenames carry no
     * version, so bumping a library to a build that ships the same names leaves the
     * list byte-identical and a stale copy would be kept and executed indefinitely.
     */
    const val FINGERPRINT: String = "88c1ad5b89505b6b"

    val FILES: List<String> = listOf(
        "katex/LICENSE",
        "katex/fonts/KaTeX_AMS-Regular.woff2",
        "katex/fonts/KaTeX_Caligraphic-Bold.woff2",
        "katex/fonts/KaTeX_Caligraphic-Regular.woff2",
        "katex/fonts/KaTeX_Fraktur-Bold.woff2",
        "katex/fonts/KaTeX_Fraktur-Regular.woff2",
        "katex/fonts/KaTeX_Main-Bold.woff2",
        "katex/fonts/KaTeX_Main-BoldItalic.woff2",
        "katex/fonts/KaTeX_Main-Italic.woff2",
        "katex/fonts/KaTeX_Main-Regular.woff2",
        "katex/fonts/KaTeX_Math-BoldItalic.woff2",
        "katex/fonts/KaTeX_Math-Italic.woff2",
        "katex/fonts/KaTeX_SansSerif-Bold.woff2",
        "katex/fonts/KaTeX_SansSerif-Italic.woff2",
        "katex/fonts/KaTeX_SansSerif-Regular.woff2",
        "katex/fonts/KaTeX_Script-Regular.woff2",
        "katex/fonts/KaTeX_Size1-Regular.woff2",
        "katex/fonts/KaTeX_Size2-Regular.woff2",
        "katex/fonts/KaTeX_Size3-Regular.woff2",
        "katex/fonts/KaTeX_Size4-Regular.woff2",
        "katex/fonts/KaTeX_Typewriter-Regular.woff2",
        "katex/katex.min.css",
        "katex/katex.min.js",
        "mermaid/LICENSE",
        "mermaid/mermaid.min.js",
        "marked/LICENSE.md",
        "marked/marked.umd.js",
        "marked-highlight/LICENSE",
        "marked-highlight/marked-highlight.umd.js",
        "highlight/LICENSE",
        "highlight/github-dark.min.css",
        "highlight/github.min.css",
        "highlight/highlight.min.js",
        "tailwind/LICENSE",
        "tailwind/tailwind.min.js",
        "babel/LICENSE",
        "babel/babel.min.js",
        "react/LICENSE",
        "react/react.production.min.js",
        "react-dom/LICENSE",
        "react-dom/react-dom.production.min.js",
    )
}
